# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a3d3bc7327cd07a759b1425321179db603c599eb19c3e61925ab4503c92ff29bd86c3f18e99e21b55b60ca056302f63b0ec37518326a4a25b84e38e24c8c4e5

test:
  secret_key_base: fb822265bd535479d9681ef8d9176f9a8c5df32c825966e5af7586a74c5da12d868f69e2eb598268086b1fb008987300919ec57fe6f970ff702d5be18c8d5372

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
